const Data4 = [
    {
        id: "1",
        img: require('../image/bag.jpg'),
        name:"Allen Solly",
        type:"Purple Solid Sling Bag",
        price:"₹1839",
        Mrp:"₹2299",
        disc:"(20% OFF)",
        txt:'inclusive of all taxes',
        size:"Select Size",
        choose_size:"Onesize",
        Qty:1,
        orderid:"ORDER # OD3255669885"
    },
    {
        id: "2",
        img: require('../image/bag.jpg'),
        name:"Allen Solly",
        type:"Purple Solid Sling Bag",
        price:"₹1839",
        Mrp:"₹2299",
        disc:"(20% OFF)",
        txt:'inclusive of all taxes',
        size:"Select Size",
        choose_size:"Onesize",
        orderid:"ORDER # OD3255669885",
        Qty:1
    },
    {
        id: "3",
        img: require('../image/bag.jpg'),
        name:"Allen Solly",
        type:"Purple Solid Sling Bag",
        price:"₹1839",
        Mrp:"₹2299",
        disc:"(20% OFF)",
        txt:'inclusive of all taxes',
        size:"Select Size",
        choose_size:"Onesize",
        Qty:1,
        orderid:"ORDER # OD3255669885"
    },
    {
        id: "4",
        img: require('../image/bag.jpg'),
        name:"Allen Solly",
        type:"Purple Solid Sling Bag",
        price:"₹1839",
        Mrp:"₹2299",
        disc:"(20% OFF)",
        txt:'inclusive of all taxes',
        size:"Select Size",
        choose_size:"Onesize",
        Qty:1,
        orderid:"ORDER # OD3255669885"
    },
    {
        id: "5",
        img: require('../image/bag.jpg'),
        name:"Allen Solly",
        type:"Purple Solid Sling Bag",
        price:"₹1839",
        Mrp:"₹2299",
        disc:"(20% OFF)",
        txt:'inclusive of all taxes',
        size:"Select Size",
        choose_size:"Onesize",
        Qty:1,
        orderid:"ORDER # OD3255669885"
    },
    {
        id: "6",
        img: require('../image/bag.jpg'),
        name:"Allen Solly",
        type:"Purple Solid Sling Bag",
        price:"₹1839",
        Mrp:"₹2299",
        disc:"(20% OFF)",
        txt:'inclusive of all taxes',
        size:"Select Size",
        choose_size:"Onesize",
        Qty:1,
        orderid:"ORDER # OD3255669885"
    },
    {
        id: "7",
        img: require('../image/bag.jpg'),
        name:"Allen Solly",
        type:"Purple Solid Sling Bag",
        price:"₹1839",
        Mrp:"₹2299",
        disc:"(20% OFF)",
        txt:'inclusive of all taxes',
        size:"Select Size",
        choose_size:"Onesize",
        Qty:1,
        orderid:"ORDER # OD3255669885"
    },
    {
        id: "8",
        img: require('../image/bag.jpg'),
        name:"Allen Solly",
        type:"Purple Solid Sling Bag",
        price:"₹1839",
        Mrp:"₹2299",
        disc:"(20% OFF)",
        txt:'inclusive of all taxes',
        size:"Select Size",
        choose_size:"Onesize",
        Qty:1,
        orderid:"ORDER # OD3255669885"
    },
    {
        id: "9",
        img: require('../image/bag.jpg'),
        name:"Allen Solly",
        type:"Purple Solid Sling Bag",
        price:"₹1839",
        Mrp:"₹2299",
        disc:"(20% OFF)",
        txt:'inclusive of all taxes',
        size:"Select Size",
        choose_size:"Onesize",
        Qty:1,
        orderid:"ORDER # OD3255669885"
    },
    {
        id: "10",
        img: require('../image/bag.jpg'),
        name:"Allen Solly",
        type:"Purple Solid Sling Bag",
        price:"₹1839",
        Mrp:"₹2299",
        disc:"(20% OFF)",
        txt:'inclusive of all taxes',
        size:"Select Size",
        choose_size:"Onesize",
        Qty:1,
        orderid:"ORDER # OD3255669885"
    },
    {
        id: "11",
        img: require('../image/bag.jpg'),
        name:"Allen Solly",
        type:"Purple Solid Sling Bag",
        price:"₹1839",
        Mrp:"₹2299",
        disc:"(20% OFF)",
        txt:'inclusive of all taxes',
        size:"Select Size",
        choose_size:"Onesize",
        Qty:1,
        orderid:"ORDER # OD3255669885"
    },
] 
export default Data4;